"""initial schema

Revision ID: 03aceb24c7b1
Revises:
Create Date: 2026-08-29 16:54:35.660338

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "03aceb24c7b1"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "guild_forum_channel",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("channel_id", sa.Integer(), nullable=False),
        sa.Column("guild_id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_guild_forum_channel")),
        sa.UniqueConstraint(
            "channel_id", name=op.f("uq_guild_forum_channel_channel_id")
        ),
    )
    op.create_table(
        "problems",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("problem_id", sa.Integer(), nullable=False),
        sa.Column("problem_frontend_id", sa.Integer(), nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("difficulty", sa.Integer(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("premium", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_problems")),
        sa.UniqueConstraint(
            "problem_frontend_id", name=op.f("uq_problems_problem_frontend_id")
        ),
        sa.UniqueConstraint("problem_id", name=op.f("uq_problems_problem_id")),
    )
    op.create_table(
        "topic_tags",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tag_name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_topic_tags")),
        sa.UniqueConstraint("tag_name", name=op.f("uq_topic_tags_tag_name")),
    )
    op.create_table(
        "guild_forum_channel_tags",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("forum_channel_id", sa.Integer(), nullable=False),
        sa.Column("tag_name", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["forum_channel_id"],
            ["guild_forum_channel.id"],
            name=op.f(
                "fk_guild_forum_channel_tags_forum_channel_id_guild_forum_channel"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_guild_forum_channel_tags")),
    )
    op.create_table(
        "problem_tags",
        sa.Column("problem_id", sa.Integer(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["problem_id"],
            ["problems.id"],
            name=op.f("fk_problem_tags_problem_id_problems"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["topic_tags.id"],
            name=op.f("fk_problem_tags_tag_id_topic_tags"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("problem_id", "tag_id", name=op.f("pk_problem_tags")),
    )
    op.create_table(
        "problem_threads",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("problem_db_id", sa.Integer(), nullable=False),
        sa.Column("forum_channel_db_id", sa.Integer(), nullable=False),
        sa.Column("thread_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["forum_channel_db_id"],
            ["guild_forum_channel.id"],
            name=op.f("fk_problem_threads_forum_channel_db_id_guild_forum_channel"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["problem_db_id"],
            ["problems.id"],
            name=op.f("fk_problem_threads_problem_db_id_problems"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_problem_threads")),
        sa.UniqueConstraint("thread_id", name=op.f("uq_problem_threads_thread_id")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("problem_threads")
    op.drop_table("problem_tags")
    op.drop_table("guild_forum_channel_tags")
    op.drop_table("topic_tags")
    op.drop_table("problems")
    op.drop_table("guild_forum_channel")
    # ### end Alembic commands ###
