"""add leetcode_discord_link table

Revision ID: 2f00cce5c762
Revises: 03aceb24c7b1
Create Date: 2026-09-03 22:03:52.568605

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '2f00cce5c762'
down_revision: str | Sequence[str] | None = '03aceb24c7b1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leetcode_discord_link',
    sa.Column('discord_user_id', sa.Integer(), nullable=False),
    sa.Column('leetcode_user_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('discord_user_id', name=op.f('pk_leetcode_discord_link')),
    sa.UniqueConstraint('leetcode_user_name', name=op.f('uq_leetcode_discord_link_leetcode_user_name'))
    )
    with op.batch_alter_table('guild_forum_channel', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_guild_forum_channel_channel_id'), ['channel_id'])

    with op.batch_alter_table('problem_threads', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_problem_threads_thread_id'), ['thread_id'])

    with op.batch_alter_table('problems', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_problems_problem_frontend_id'), ['problem_frontend_id'])
        batch_op.create_unique_constraint(batch_op.f('uq_problems_problem_id'), ['problem_id'])

    with op.batch_alter_table('topic_tags', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_topic_tags_tag_name'), ['tag_name'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topic_tags', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_topic_tags_tag_name'), type_='unique')

    with op.batch_alter_table('problems', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_problems_problem_id'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_problems_problem_frontend_id'), type_='unique')

    with op.batch_alter_table('problem_threads', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_problem_threads_thread_id'), type_='unique')

    with op.batch_alter_table('guild_forum_channel', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_guild_forum_channel_channel_id'), type_='unique')

    op.drop_table('leetcode_discord_link')
    # ### end Alembic commands ###
