name: Run tests

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

permissions:
  contents: read

jobs:
  build:
    name: Run Pytest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Set up uv
        uses: astral-sh/setup-uv@v10.0.1
        with:
          enable-cache: true

      - name: Install dependencies and test
        run: |
          uv sync --dev
          uv run pytest -v -ra
